### PR TITLE
Support creating excalidraw file from File->New and Command P

### LINKED ISSUE #21: New command: Create a new untitled Excalidraw file
We should also integrate with the `Create: New File...` command.

### PR DESCRIPTION
**Pull request by rebornix**
Fixes #21.

This PR added a "New Excalidraw File" command to both the File Menu and Command Palette.

image

image

### CODE REVIEW

**Comment by pomdtr** [comment]
Thanks for the contribution !

I think the language detection feature of vscode is playing against us here. If I hit save on the new untitled excalidraw file, the extension propose to save it as `Excalidraw-1.excalidraw.json` instead of `Excalidraw-1.excalidraw`

I would prefer it we could avoid this. Do you have an idea how to disable this behaviour ?

**Comment by pomdtr** [comment]
I just looked at the tldraw extension, and it looks like it has the same issue.

**Comment by rebornix** [comment]
@pomdtr it looks like a bug in the custom editor file saving. Let's create an issue upstream and have it tracked there.

**Comment by rebornix** [comment]
@pomdtr are you seeing the wrong file extension all the time, I don't seem to reproduce though

image

**Comment by pomdtr** [comment]
Did you edit the drawing before saving it ? It looks like the `.json` extension is added as soon as the document contains a json string.

I also use the simple file picker, so it could be related to this.

**Comment by rebornix** [comment]
@pomdtr good catch, as long as the document is not dirty, it will use `json` as file extension.

**Comment by pomdtr** [comment]
I found another issue.

If you create a new untitled document, close it, and then create one again: vscode throw an error and the new document does not open

**Comment by pomdtr** [comment]
FYI, I did close this pr since the extension now use customDocument instead of customTextDocument.

**Pull request closed without merging**
