### PR TITLE
Set default theme to `auto`

### PR DESCRIPTION
**Pull request by fultonm**
Update package.json to Set default theme to auto

This allows the extension to automatically respect the user's preference for light or dark mode.

### CODE REVIEW

**Comment by pomdtr** [comment]
Hey, thanks for taking the time to contribute to the extension.

I'm not sure this make sense for excalidraw drawings. 
The website default to light mode, even when the system theme is dark.

**Comment by fultonm** [comment]
I see, then it wasn’t an oversight in these settings, but rather a design choice.

I wonder what the advantage of editing in light mode is, despite the user having a preconfigured preference for dark mode?

I can see some more rationale to default to light mode when exporting drawings, since everyone else will view the drawings and we don’t know their preference… but editing is something only this user will do

One very nice things about Excalidraw is the color palette looks nice and readable in dark or light mode. So there’s no issue with editing in dark and exporting in light, right?

**Comment by pomdtr** [comment]
I think it was set to auto at first, but it confused some users (as they did not know how to configure it to appear the same way as in the website).

I think people actively searching for the dark mode will be able to find it. I'll try to get some feedback from the team on this. They might have encounter the same issue on the website and decided against a dynamic theme.

**Comment by fultonm** [comment]
Got it, that makes sense to maintain parity between website and extension behavior. Although I would say the website version (and all websites that implement a dark mode) should also respect the browsers theme preferences when loading a default theme. Maybe that’s a separate discussion.

Is there a technical limitation that prevents setting Dark Mode using the hamburger menu like on the website?

**Comment by pomdtr** [comment]
I don't think so, the extension was created before the excalidraw component started supporting this kind of customisation.

It is definitely possible to add support for it now!

**Comment by fultonm** [comment]
Cool. I use this tool a lot in my day job, so I would love to contribute this when I can find the time.

Basically, my physical laptop is a very locked down device and does not allow access to the internet. Although I can access remote machines via RDP which *can* access the internet and use Excalidraw for web, I then have to deal with RDP lag while designing. But, the laptop does have VS Code and allows extensions to be installed.

So, this extension has been a wonderful solution for me, so thank you for all your work on it.

**Comment by pomdtr** [comment]
Thanks for the nice words! Contributions are definitely welcome :)

**Pull request closed without merging**
